/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */
import PushNotificationIOS from "@react-native-community/push-notification-ios";
import PushNotification from "react-native-push-notification";

import React, { useEffect, useState } from 'react';

import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { useStoreState } from 'easy-peasy';
import { api, observable } from './store';
import { StoreProvider } from 'easy-peasy';
import { useNavigationContainerRef } from "@react-navigation/core";

import Settings from "./Component/Page/Settings";
import Home from "./Component/Page/Home";
import Startup from "./Component/Startup/index";
import Loader from "./Component/Tool/Loader";
import Discover from "./Component/Page/Discover";

const HomeStack = createNativeStackNavigator()
const defaultView = {
	headerShown: false,
	contentStyle: {
		backgroundColor: 'white'
	}
}

const App = () => {
	return (
		<StoreProvider store={observable}>
			<Root/>
		</StoreProvider>
	)
};

const Root = () => {

	const update = useStoreState((state) => state.update)
	const navigationMode = useStoreState((state) => state.navigationMode)
	const [loaded, setLoaded] = useState(false)
	const [isAuth, setAuth] = useState(false)
	const navigatorRef = useNavigationContainerRef()

	useEffect(() => {
		api.isAuth()
		.then(() => setAuth(true))
		.catch(() => setAuth(false))
		.finally(() => {
			if (!loaded)
				setLoaded(true)
		})
	}, [update])

	useEffect(() => {
		if (navigatorRef.isReady() && loaded && !isAuth) {
			console.log("Is not auth so redirect to Login/Register page")
			navigatorRef.navigate('Startup')
		}
	}, [isAuth, loaded])

	return (
		<NavigationContainer ref={navigatorRef}>
			<HomeStack.Navigator 
			initialRouteName="Home" 
			screenOptions={{
				presentation: navigationMode,
				headerBackVisible: false
			}}>
				{loaded ? <>
					{/* NAVIGATION */}
					<HomeStack.Screen component={Home} name="Home" options={defaultView}/>
					<HomeStack.Screen component={Settings} name="Settings" options={defaultView}/>
					<HomeStack.Screen component={Discover} name="Discover" options={defaultView}/>
					{/* AUTH CONTROLLER GUARD */}
					<HomeStack.Screen component={Startup} name="Startup" options={{...defaultView, gestureEnabled: isAuth}}/>
					</> : 
					<HomeStack.Screen component={Loader} name="Loading" options={defaultView}/> // LOADER
				}
			</HomeStack.Navigator>
		</NavigationContainer>
	)
}

// PushNotification.localNotification({
// 	/* iOS and Android properties */
// 	id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
// 	title: "My Notification Title", // (optional)
// 	message: "My Notification Message", // (required)
// 	userInfo: {}, // (optional) default: {} (using null throws a JSON value '<null>' error)
// 	playSound: false, // (optional) default: true
// 	soundName: "default", // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
// 	number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
// 	repeatType: "day", // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
// })

// Must be outside of any component LifeCycle (such as `componentDidMount`).
// PushNotification.configure({
//   // (optional) Called when Token is generated (iOS and Android)
//   onRegister: function (token) {
//     console.log("TOKEN:", token);
//   },

//   // (required) Called when a remote is received or opened, or local notification is opened
//   onNotification: function (notification) {
//     console.log("NOTIFICATION:", notification);

//     // process the notification

//     // (required) Called when a remote is received or opened, or local notification is opened
//     notification.finish(PushNotificationIOS.FetchResult.NoData);
//   },

//   // (optional) Called when Registered Action is pressed and invokeApp is false, if true onNotification will be called (Android)
//   onAction: function (notification) {
//     console.log("ACTION:", notification.action);
//     console.log("NOTIFICATION:", notification);

//     // process the action
//   },

//   // (optional) Called when the user fails to register for remote notifications. Typically occurs when APNS is having issues, or the device is a simulator. (iOS)
//   onRegistrationError: function(err) {
//     console.error(err.message, err);
//   },

//   // IOS ONLY (optional): default: all - Permissions to register.
//   permissions: {
//     alert: true,
//     badge: true,
//     sound: true,
//   },

//   // Should the initial notification be popped automatically
//   // default: true
//   popInitialNotification: true,

//   /**
//    * (optional) default: true
//    * - Specified if permissions (ios) and token (android and ios) will requested or not,
//    * - if not, you must call PushNotificationsHandler.requestPermissions() later
//    * - if you are not using remote notification or do not have Firebase installed, use this:
//    *     requestPermissions: Platform.OS === 'ios'
//    */
//   requestPermissions: true,
// });

export default App;
